import { User } from '../models/User';
import { Profile } from '../models/Profile';
import { Match } from '../models/Match';
import { Report } from '../models/Report';
import { Chat } from '../models/Chat';
import { logger } from '../utils/logger';
import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { ENV } from '../config/env';

// Initialize Gemini SDK if API key is provided
let genAI: GoogleGenerativeAI | null = null;
if (ENV.GEMINI_API_KEY && ENV.GEMINI_API_KEY !== 'YourGeminiApiKeyHere') {
  genAI = new GoogleGenerativeAI(ENV.GEMINI_API_KEY);
}

export class AIFraudService {
  /**
   * Run an Advanced Trust Score scan over all active users.
   * Decrements trust score for suspicious behaviors.
   * Returns the number of users flagged/shadowbanned.
   */
  static async scanCluster(): Promise<number> {
    try {
      logger.info('[AIFraudService] Initiating advanced behavioral trust scan...');
      
      const activeUsers = await User.find({ status: 'active', isShadowBanned: false });
      let shadowbanCount = 0;

      for (const user of activeUsers) {
        const profile = await Profile.findOne({ user: user._id });
        let trustPenalty = 0;
        let duplicateFound = false;
        let duplicateDetailsText = '';
        let aiGeneratedFound = false;
        let aiGeneratedConfidence = 0;
        let aiRationale = '';
        let fakePhoneFound = false;
        let phoneInfo = '';
        let chatSpamFound = false;
        let spamInfo = '';

        // --- Heuristic 1: Profile Completeness Anomaly ---
        if (!profile) {
          trustPenalty += 100; // Ghost account
        } else {
          if (!profile.bio || profile.bio.length < 15) trustPenalty += 30;
          if (profile.photos && profile.photos.length <= 1) trustPenalty += 20;
          if (!profile.career?.occupation && !profile.occupation && !profile.education) trustPenalty += 15;

          // Bio keyword scanning (Crypto/Grooming)
          const suspiciousKeywords = ['cashapp', 'venmo', 'sugar', 'crypto', 'investment', 'whatsapp', 'snapchat', 'kik'];
          const bioLower = profile.bio ? profile.bio.toLowerCase() : '';
          for (const keyword of suspiciousKeywords) {
            if (bioLower.includes(keyword)) trustPenalty += 30;
          }

          // Single photo + Social media handles only in bio
          if (profile.photos && profile.photos.length === 1 && (bioLower.includes('ig:') || bioLower.includes('insta'))) {
            trustPenalty += 25; // Likely an Instagram follower farming bot
          }

          // --- Heuristic 2: Duplicate Photo Checker ---
          if (profile.photos && profile.photos.length > 0) {
            for (const photoUrl of profile.photos) {
              const duplicateMatch = await Profile.findOne({
                user: { $ne: user._id },
                photos: photoUrl
              }).populate('user', 'phone email');
              if (duplicateMatch) {
                duplicateFound = true;
                trustPenalty += 40;
                duplicateDetailsText = `Duplicate profile photo found! Also used by User: ${duplicateMatch.user?._id}. `;
                break;
              }
            }
          }

          // --- Heuristic 3: AI-Generated / Stock Photo Checker (Gemini Vision) ---
          if (genAI && profile.photos && profile.photos.length > 0) {
            try {
              const primaryPhoto = profile.photos[0];
              const urlParts = primaryPhoto.split('/');
              const filename = urlParts[urlParts.length - 1];
              const filePath = path.join(__dirname, '../../uploads', filename);

              if (fs.existsSync(filePath)) {
                const imagePart = {
                  inlineData: {
                    data: fs.readFileSync(filePath).toString('base64'),
                    mimeType: 'image/jpeg'
                  }
                };
                const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
                const prompt = `
                  Analyze this user profile photo for a matrimony app.
                  Determine if the photo is AI-generated (e.g. looks synthetic, generated by Midjourney, Stable Diffusion, or shows standard generative anomalies) or a stock photo/public model portrait.
                  Return a JSON response in this strict format:
                  {
                    "isAIGenerated": true/false,
                    "isStockPhoto": true/false,
                    "confidence": 85,
                    "rationale": "Reason details..."
                  }
                `;
                const result = await model.generateContent([prompt, imagePart]);
                const responseText = result.response.text().trim();
                const cleanJson = responseText.replace(/```json|```/g, '').trim();
                const parsed = JSON.parse(cleanJson);
                if (parsed.isAIGenerated || parsed.isStockPhoto) {
                  aiGeneratedFound = true;
                  aiGeneratedConfidence = parsed.confidence || 80;
                  aiRationale = parsed.rationale || 'Flagged as synthetic or stock photo.';
                  trustPenalty += 45;
                }
              }
            } catch (err: any) {
              logger.error(`[AIFraudService] Gemini image scan failed for ${user._id}: ${err.message}`);
            }
          }
        }

        // --- Heuristic 4: Fake Phone Number Checker ---
        if (user.phone) {
          const cleanPhone = user.phone.replace(/\D/g, '');
          const isRepeating = /^(\d)\1{7,}$/.test(cleanPhone);
          const isSequential = /123456|012345|987654/.test(cleanPhone);
          if (cleanPhone.length < 10 || isRepeating || isSequential) {
            fakePhoneFound = true;
            trustPenalty += 30;
            phoneInfo = `Suspicious phone number pattern detected: ${user.phone}.`;
          }
        }

        // --- Heuristic 5: Behavioral Swipe Velocity ---
        if (user.swipeVelocity?.count && user.swipeVelocity.count > 30) {
          trustPenalty += 20; // Fast swiping
        }

        // --- Heuristic 6: Suspicious Activity (Chat Spam Copy-Paste) ---
        try {
          const userChats = await Chat.find({ participants: user._id }).lean();
          const messageMap: Record<string, Set<string>> = {};
          
          for (const chat of userChats) {
            const otherParticipant = chat.participants.find(p => p.toString() !== user._id.toString());
            if (!otherParticipant) continue;
            
            for (const msg of chat.messages || []) {
              if (msg.sender.toString() === user._id.toString() && msg.text && msg.text.length > 12) {
                if (!messageMap[msg.text]) {
                  messageMap[msg.text] = new Set();
                }
                messageMap[msg.text].add(otherParticipant.toString());
              }
            }
          }
          
          const maxRecipients = Object.values(messageMap)
            .map(recipients => recipients.size)
            .reduce((a, b) => Math.max(a, b), 0);

          if (maxRecipients >= 3) {
            chatSpamFound = true;
            trustPenalty += 35;
            spamInfo = `User is copy-pasting the exact same message to ${maxRecipients} different users.`;
          }
        } catch (err: any) {
          logger.error(`[AIFraudService] Chat spam check failed for ${user._id}: ${err.message}`);
        }

        // Apply calculated scores
        const calculatedScore = Math.max(0, 100 - trustPenalty);
        const riskScore = 100 - calculatedScore;

        user.trustScore = calculatedScore;
        await user.save();

        if (profile) {
          profile.riskScore = riskScore;
          profile.isFakeFlagged = riskScore >= 50;
          await profile.save();
        }
        
        if (calculatedScore < 50) {
          user.isShadowBanned = true;
          await user.save();
          shadowbanCount++;
          logger.warn(`[Security] Auto-Shadowbanned User ${user._id} during cluster scan. RiskScore: ${riskScore}%`);

          // Generate silent report for admin ledger
          const recentReport = await Report.findOne({
            reportedUser: user._id,
            reason: 'fake_profile',
            autoFlagged: true
          });

          if (!recentReport) {
            let alertDescription = `[AI SECURITY DETECTOR] Risk assessment score: ${riskScore}%\n`;
            if (duplicateFound) alertDescription += `• ${duplicateDetailsText}\n`;
            if (aiGeneratedFound) alertDescription += `• Photo is likely AI-generated/stock. Confidence: ${aiGeneratedConfidence}%. Rationale: ${aiRationale}\n`;
            if (fakePhoneFound) alertDescription += `• ${phoneInfo}\n`;
            if (chatSpamFound) alertDescription += `• ${spamInfo}\n`;
            if (!profile) alertDescription += `• Profile has not been created yet.\n`;
            else {
              if (!profile.bio || profile.bio.length < 15) alertDescription += `• Biography is empty or too short.\n`;
              if (profile.photos && profile.photos.length <= 1) alertDescription += `• Profile has 1 or fewer photos.\n`;
            }

            await Report.create({
              reporter: new mongoose.Types.ObjectId('000000000000000000000000'),
              reportedUser: user._id,
              reason: 'fake_profile',
              description: alertDescription,
              severity: riskScore >= 80 ? 'critical' : 'high',
              autoFlagged: true,
            });
          }
        }
      }

      logger.info(`[AIFraudService] Trust scan complete. Shadowbanned ${shadowbanCount} bots.`);
      return shadowbanCount;
    } catch (error: any) {
      logger.error(`[AIFraudService] Error running trust scan: ${error.message}`);
      throw error;
    }
  }
}
