import { Schema, model, Document, Types } from 'mongoose';

export interface IMatch extends Document {
  user1: Types.ObjectId; // User initiating action or smaller ID for unique indexing
  user2: Types.ObjectId; // Counterparty user
  status: 'pending' | 'liked' | 'passed' | 'matched';
  compatibilityScore?: number; // Calculated compatibility score (0-100)
  aiReasoning?: string; // Explanation generated by Gemini API
  actionBy?: Types.ObjectId; // User who took the last action
  createdAt: Date;
  updatedAt: Date;
}

const MatchSchema = new Schema<IMatch>(
  {
    user1: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    user2: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    status: {
      type: String,
      enum: ['pending', 'liked', 'passed', 'matched'],
      default: 'pending',
    },
    compatibilityScore: { type: Number, min: 0, max: 100 },
    aiReasoning: { type: String },
    actionBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

// Prevent duplicate match records between two users by enforcing small-id first order
MatchSchema.index({ user1: 1, user2: 1 }, { unique: true });
MatchSchema.index({ status: 1, actionBy: 1 });
MatchSchema.index({ user1: 1, status: 1 });
MatchSchema.index({ user2: 1, status: 1 });

export const Match = model<IMatch>('Match', MatchSchema);
export default Match;
